name: The Daane Lab at the University of Houston
description: Evolutionary and developmental genetics @ UH
url: http://www.daanelab.org

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
  id: G-0QS1L7TNZ5          # Required - replace with your tracking id
